"""initial schema

Revision ID: 9de205bfdf73
Revises: 
Create Date: 2026-09-09 22:40:35.042554
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9de205bfdf73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('video_chunk', 'config', 'audio_media', name='contenttype', native_enum=False, length=32), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('video_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('source_machine', sa.String(length=255), nullable=True),
    sa.Column('source_system_tag', sa.String(length=255), nullable=True),
    sa.Column('backup_category', sa.Enum('project_archive', 'machine_drive_backup', name='backupcategory', native_enum=False, length=32), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path', name='uq_content_source_path')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_backup_category'), ['backup_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_source_machine'), ['source_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_video_name'), ['video_name'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('write', 'verify', 'restore', 'backup', name='jobtype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', 'interrupted', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('progress_current', sa.BigInteger(), nullable=False),
    sa.Column('progress_total', sa.BigInteger(), nullable=False),
    sa.Column('progress_message', sa.String(length=512), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('library_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_kind', sa.String(length=16), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('drive_loaded_from', sa.Integer(), nullable=True),
    sa.Column('is_cleaning_tape', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_kind', 'slot_number', name='uq_slot_kind_number')
    )
    with op.batch_alter_table('library_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_slots_slot_number'), ['slot_number'], unique=False)

    op.create_table('restore_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_container_ids', sa.JSON(), nullable=False),
    sa.Column('content_item_ids', sa.JSON(), nullable=False),
    sa.Column('destination_path', sa.Text(), nullable=True),
    sa.Column('include_manifests', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'in_progress', 'completed', 'failed', 'cancelled', name='restorestatus', native_enum=False, length=16), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restore_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_requests_status'), ['status'], unique=False)

    op.create_table('sequence_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_name', sa.String(length=255), nullable=True),
    sa.Column('shot_name', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_machine', sa.String(length=255), nullable=True),
    sa.Column('backup_category', sa.Enum('project_archive', 'machine_drive_backup', name='backupcategory', native_enum=False, length=32), nullable=False),
    sa.Column('frame_start', sa.Integer(), nullable=True),
    sa.Column('frame_end', sa.Integer(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('has_gaps', sa.Boolean(), nullable=False),
    sa.Column('gap_detail', sa.Text(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('manifest_ref', sa.Text(), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path', name='uq_sequence_source_path')
    )
    with op.batch_alter_table('sequence_containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequence_containers_backup_category'), ['backup_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_containers_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_containers_sequence_name'), ['sequence_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_containers_shot_name'), ['shot_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_containers_source_machine'), ['source_machine'], unique=False)

    op.create_table('tapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('lto_generation', sa.String(length=16), nullable=True),
    sa.Column('capacity_native_bytes', sa.BigInteger(), nullable=True),
    sa.Column('capacity_compressed_bytes', sa.BigInteger(), nullable=True),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('scratch', 'active', 'full', 'archived', 'retired', 'damaged', name='tapestatus', native_enum=False, length=16), nullable=False),
    sa.Column('first_written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('write_pass_count', sa.Integer(), nullable=False),
    sa.Column('physical_location', sa.String(length=128), nullable=True),
    sa.Column('offsite_pair_tape_id', sa.Integer(), nullable=True),
    sa.Column('dedicated_source_machine', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offsite_pair_tape_id'], ['tapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tapes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tapes_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_tapes_status'), ['status'], unique=False)

    op.create_table('content_tape_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tape_id', sa.Integer(), nullable=False),
    sa.Column('ltfs_path', sa.Text(), nullable=False),
    sa.Column('sequence_container_id', sa.Integer(), nullable=True),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('byte_range_start', sa.BigInteger(), nullable=True),
    sa.Column('byte_range_end', sa.BigInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(sequence_container_id IS NOT NULL) <> (content_item_id IS NOT NULL)', name='ck_span_exactly_one_parent'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_container_id'], ['sequence_containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tape_id'], ['tapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_tape_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_tape_spans_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_tape_spans_sequence_container_id'), ['sequence_container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_tape_spans_tape_id'), ['tape_id'], unique=False)

    op.create_table('read_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tape_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('ltfs_path', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tape_id'], ['tapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('read_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_errors_tape_id'), ['tape_id'], unique=False)

    op.create_table('tape_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tape_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('load', 'unload', 'write', 'verify', 'inventory', 'format', 'clean', 'retire', 'eject', name='tapeeventtype', native_enum=False, length=16), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('drive_number', sa.Integer(), nullable=True),
    sa.Column('initiated_by', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('pending', 'success', 'error', 'partial', name='eventresult', native_enum=False, length=16), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tape_id'], ['tapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tape_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tape_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tape_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tape_events_tape_id'), ['tape_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tape_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tape_events_tape_id'))
        batch_op.drop_index(batch_op.f('ix_tape_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_tape_events_event_type'))

    op.drop_table('tape_events')
    with op.batch_alter_table('read_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_errors_tape_id'))

    op.drop_table('read_errors')
    with op.batch_alter_table('content_tape_spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_tape_spans_tape_id'))
        batch_op.drop_index(batch_op.f('ix_content_tape_spans_sequence_container_id'))
        batch_op.drop_index(batch_op.f('ix_content_tape_spans_content_item_id'))

    op.drop_table('content_tape_spans')
    with op.batch_alter_table('tapes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tapes_status'))
        batch_op.drop_index(batch_op.f('ix_tapes_barcode'))

    op.drop_table('tapes')
    with op.batch_alter_table('sequence_containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequence_containers_source_machine'))
        batch_op.drop_index(batch_op.f('ix_sequence_containers_shot_name'))
        batch_op.drop_index(batch_op.f('ix_sequence_containers_sequence_name'))
        batch_op.drop_index(batch_op.f('ix_sequence_containers_project_name'))
        batch_op.drop_index(batch_op.f('ix_sequence_containers_backup_category'))

    op.drop_table('sequence_containers')
    with op.batch_alter_table('restore_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_requests_status'))

    op.drop_table('restore_requests')
    with op.batch_alter_table('library_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_slots_slot_number'))

    op.drop_table('library_slots')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_video_name'))
        batch_op.drop_index(batch_op.f('ix_content_items_source_machine'))
        batch_op.drop_index(batch_op.f('ix_content_items_project_name'))
        batch_op.drop_index(batch_op.f('ix_content_items_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_items_backup_category'))

    op.drop_table('content_items')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
